Added support for Illumos
uutils/platform-info pull request #48
Opened 2023-06-12 14:51 UTC by siepkes

This commit introduces support for Illumos, an (Open) Solaris derivative. 

`uname -o` on Illumos returns `illumos`.

It also clarifies the documentation a bit on why the domainname field is missing for OS'es like the BSD's and Illumos.

2023-06-12 14:59 UTC, siepkes commented
It seems Github actions dies on a style check in an integration test. Oddly enough this PR doesn't change that code. I think the style check might have been updated? Causing it to suddenly fail on this piece of existing code?

```
error: redundant clone
  --> tests/integration_test.rs:51:25
   |
51 |     let info_copy = info.clone();
   |                         ^^^^^^^^ help: remove this
   |
note: cloned value is neither consumed nor mutated
  --> tests/integration_test.rs:51:21
   |
51 |     let info_copy = info.clone();
   |                     ^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
   = note: `-D clippy::redundant-clone` implied by `-D warnings`

error: could not compile `platform-info` (test "integration_test") due to previous error
warning: build failed, waiting for other jobs to finish...
error: redundant clone
```

2023-06-13 03:28 UTC, rivy commented
Hmm, odd that it didn't show up as failures in the prior merge with the CI code change.
I'll fix it and you can rebase onto the new 'main'.

2023-06-13 03:32 UTC, rivy requested changes
Minor nit... we generally use active/imperative voice for commit messages.
When you rebase onto the new 'main', would you mind changing the commit message to "add support for Illumos"?

2023-06-13 03:50 UTC, rivy commented
@siepkes , the updated 'main' is now available. If you rebase, I expect that all tests should pass.

2023-06-13 07:45 UTC, siepkes commented
Your changes seem to have worked. All checks passed!

2023-06-13 12:33 UTC, merged